name: failures_example
description: An example of using failures package
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  failures: ^0.0.1
  flutter:
    sdk: flutter
  multi_logger: ^0.0.1
  sentry_flutter: ^8.14.2
  slang: ^4.7.0
  slang_flutter: ^4.7.0

dev_dependencies:
  failures_builder: 0.0.1
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  slang_build_runner: ^4.7.0

flutter:
  uses-material-design: true
