name: failures
description: Gracefully handle failures in your Dart/Flutter application
version: 0.0.10
repository: https://github.com/dsvishchov/failures
issue_tracker: https://github.com/dsvishchov/failures/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.0
  meta: ^1.9.0
  stack_trace: ^1.12.0
