name: failures_builder
description: A code generator companion for failures
version: 0.0.1
repository: https://github.com/dsvishchov/failures
issue_tracker: https://github.com/dsvishchov/failures/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.3
  failures: 0.0.1
  meta: ^1.9.0
  source_gen: ^4.1.0
