name: failures_builder
description: A code generator companion for failures
version: 0.0.11
repository: https://github.com/dsvishchov/failures
issue_tracker: https://github.com/dsvishchov/failures/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analyzer: ">=8.0.0 <9.0.0"
  build: ">=3.0.0 <5.0.0"
  failures: ^0.0.11
  meta: ^1.9.0
  source_gen: ">=3.0.0 <5.0.0"
